baseURL = "http://example.org/"
DefaultContentLanguage = "en"

[Languages]
[Languages.en]
title = "Multilingual Hugo Example"
weight = 0
languagename = "English"

[[Languages.en.menu.main]]
url = "/"
name = "Home"
weight = 1

[[Languages.en.menu.main]]
url = "/about/"
name = "About"
weight = 0

[Languages.fr]
title = "Multilingue Exemple Hugo"
weight = 1
languagename = "Français"

[[Languages.fr.menu.main]]
url = "/"
name = "d'Accueil"
weight = 1

[[Languages.fr.menu.main]]
url = "/a-propos/"
name = "À propos"
weight = 0

